services:
 nova-postgres:
  image: postgres:17-alpine
  container_name: nova-postgres
  expose:
   - "5432"
  environment:
   POSTGRES_USER: ${POSTGRES_USER:-postgres}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
   POSTGRES_DB: ${POSTGRES_DB:-postgres}
  volumes:
   - nova_postgres_data:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD-SHELL", 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
   interval: 5s
   timeout: 5s
   retries: 5
  restart: unless-stopped

 migrate:
  image: "starlightv/nova-status-migrate:latest"
  environment:
   DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@nova-postgres:5432/${POSTGRES_DB:-postgres}
   SKIP_VALIDATION: "true"
  depends_on:
   nova-postgres:
    condition: service_healthy
  restart: "no"

 nova-app:
  image: "starlightv/nova-status-app:latest"
  expose:
   - "3000"
  environment:
   NODE_ENV: production
   DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@nova-postgres:5432/${POSTGRES_DB:-postgres}
   BETTER_AUTH_URL: ${BETTER_AUTH_URL}
   NEXT_PUBLIC_BETTER_AUTH_URL: ${NEXT_PUBLIC_BETTER_AUTH_URL}
   BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
   BETTER_AUTH_GITHUB_CLIENT_ID: ${BETTER_AUTH_GITHUB_CLIENT_ID}
   BETTER_AUTH_GITHUB_CLIENT_SECRET: ${BETTER_AUTH_GITHUB_CLIENT_SECRET}
   JWT_SECRET: ${JWT_SECRET}
  depends_on:
   migrate:
    condition: service_completed_successfully
  restart: unless-stopped

volumes:
 nova_postgres_data:
