import "~/styles/globals.css";

import type { Metadata } from "next";
import {Nunito, Nunito_Sans } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { HydrateClient } from "~/trpc/server";
import { TooltipProvider } from "~/components/ui/tooltip";
import { getAuth } from "~/lib/auth";
import { SessionProvider } from "~/provider/session-provider";

const nunitoSans = Nunito_Sans({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


const nunito = Nunito({
	subsets: ["latin"],
	variable: "--font-nunito",
	weight: ["400", "500", "600", "700"],
	style: ["normal", "italic"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getAuth()
  return (
    <html lang="en" 	className={cn("dark", nunito.variable, "font-sans", nunitoSans.variable)}>
     	<head>
				<meta name="darkreader-lock" />
			</head>
      <body>
        <SessionProvider initialSession={session}>
        <TRPCReactProvider>
          <HydrateClient>
            <TooltipProvider>{children}</TooltipProvider>
          </HydrateClient>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
